// <auto-generated />
namespace DB_lib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Columns_AntwortName_ZusatzinfoName05_01_2018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Columns_AntwortName_ZusatzinfoName05_01_2018));
        
        string IMigrationMetadata.Id
        {
            get { return "201801051340164_Columns_AntwortName_ZusatzinfoName05_01_2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
