//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infocontent
    {
        public int InfoContentID { get; set; }
        public string InfoContent1 { get; set; }
        public string Heading { get; set; }
        public int FkZusatzinfo { get; set; }
    
        public virtual Zusatzinfo Zusatzinfo { get; set; }
    }
}
