//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paar
    {
        public int PaarID { get; set; }
        public string Teil1 { get; set; }
        public string Teil2 { get; set; }
        public int FkAntwortVerbinden { get; set; }
    
        public virtual Antwort_verbinden Antwort_verbinden { get; set; }
    }
}
