//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radiobutton
    {
        public int RadioButtonsID { get; set; }
        public string Content { get; set; }
        public bool ErwartungsWert { get; set; }
        public int FkAntwortRadiobuttons { get; set; }
    
        public virtual Antwort_radiobutton Antwort_radiobutton { get; set; }
    }
}
