//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_lib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WissenstestDBEntities : DbContext
    {
        public WissenstestDBEntities()
            : base("name=WissenstestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admintabelle> Admintabelle { get; set; }
        public virtual DbSet<Antwort> Antwort { get; set; }
        public virtual DbSet<Antwort_checkbox> Antwort_checkbox { get; set; }
        public virtual DbSet<Antwort_datepicker> Antwort_datepicker { get; set; }
        public virtual DbSet<Antwort_radiobutton> Antwort_radiobutton { get; set; }
        public virtual DbSet<Antwort_slider> Antwort_slider { get; set; }
        public virtual DbSet<Antwort_text> Antwort_text { get; set; }
        public virtual DbSet<Antwort_verbinden> Antwort_verbinden { get; set; }
        public virtual DbSet<Bezirk> Bezirk { get; set; }
        public virtual DbSet<Checkbox> Checkbox { get; set; }
        public virtual DbSet<Frage> Frage { get; set; }
        public virtual DbSet<Hintergrund> Hintergrund { get; set; }
        public virtual DbSet<Infocontent> Infocontent { get; set; }
        public virtual DbSet<Paar> Paar { get; set; }
        public virtual DbSet<Radiobutton> Radiobutton { get; set; }
        public virtual DbSet<Standort> Standort { get; set; }
        public virtual DbSet<Station> Station { get; set; }
        public virtual DbSet<Stufe> Stufe { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Typendefinition> Typendefinition { get; set; }
        public virtual DbSet<Zusatzinfo> Zusatzinfo { get; set; }
        public virtual DbSet<Aufgabe> Aufgabe { get; set; }
        public virtual DbSet<Bild> Bild { get; set; }
    }
}
